name = "AIRDW"
license = "MIT"
description = "A theme for blog.air.mn based on Hugo Clarity."
homepage = "https://blog.air.mn"
tags = ["dark", "technical", "blog"]
features = ["dark", "technical", "blog"]
min_version = "0.91.0"

[author]
  name = "Berjan B"
  homepage = "https://blog.air.mn"

# Authors of Hugo Clarity
original = [
  {name = "Chip Zoller", homepage = "https://neonmirrors.net"},
  {name = "Dan Weru", homepage = "https://github.com/onweru"},
  {name = "Ivan Boothe", homepage = "https://rootwork.org"}
]
